version: '3.4'
services:
  expvl.clinicapp.frontend:
    image: expvl.clinicapp.frontend:v1.2
    build: 
      context: ./ClinicApp.FrontEnd
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9086:80
    depends_on:
      - clinicapp.backend.proxy 
  expvl.clinicapp.backend.proxy:
    image: nginx:latest
    ports:
      - 9088:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - expvl.clinicapp.authorizationandusermanager
    - expvl.clinicapp.infrastructure
    - expvl.clinicapp.client
    - expvl.clinicapp.servicelog
    - expvl.clinicapp.contractor
    - expvl.clinicapp.billing
    - expvl.clinicapp.dashboard
    - expvl.clinicapp.excelgen
  expvl.clinicapp.billing:
    image: expvl.clinicapp.billing:v1.2
    build:
      context: .
      dockerfile: ClinicApp.MSBilling/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=epvl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  expvl.clinicapp.dashboard:
    image: expvl.clinicapp.dashboard:v1.2
    build:
      context: .
      dockerfile: ClinicApp.MSDashboard/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=epvl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  expvl.clinicapp.excelgen:
    image: expvl.clinicapp.excelgen:v1.2
    build:
      context: .
      dockerfile: ClinicApp.MSExcelGen/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=epvl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  expvl.clinicapp.authorizationandusermanager:
    image: expvl.clinicapp.authorizationandusermanager:v1.2
    build:
      context: .
      dockerfile: ClinicApp.AuthorizationAndUserManager/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=epvl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  expvl.clinicapp.client:
    image: expvl.clinicapp.client:v1.2
    build:
      context: .
      dockerfile: ClinicApp.Client/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=epvl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  expvl.clinicapp.contractor:
    image: expvl.clinicapp.contractor:v1.2
    build:
      context: .
      dockerfile: ClinicApp.Contractor/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=epvl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  expvl.clinicapp.infrastructure:
    image: expvl.clinicapp.infrastructure:v1.2
    build:
      context: .
      dockerfile: ClinicApp.MSInfrastructure/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=epvl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  expvl.clinicapp.servicelog:
    image: expvl.clinicapp.servicelog:v1.2
    build:
      context: .
      dockerfile: ClinicApp.ServiceLog/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=epvl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"