version: '3.4'
services:
  principles.clinicapp.frontend:
    image: principles.clinicapp.frontend:v1.2
    build: 
      context: ./ClinicApp.FrontEnd
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8286:80
    depends_on:
      - principles.clinicapp.backend.proxy 
  principles.clinicapp.backend.proxy:
    image: nginx:latest
    ports:
      - 8284:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - principles.clinicapp.authorizationandusermanager
    - principles.clinicapp.infrastructure
    - principles.clinicapp.client
    - principles.clinicapp.servicelog
    - principles.clinicapp.contractor
    - principles.clinicapp.billing
    - principles.clinicapp.dashboard
    - principles.clinicapp.excelgen
  principles.clinicapp.billing:
    image: principles.clinicapp.billing:v1.2
    build:
      context: .
      dockerfile: ClinicApp.MSBilling/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=pl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  principles.clinicapp.dashboard:
    image: principles.clinicapp.dashboard:v1.2
    build:
      context: .
      dockerfile: ClinicApp.MSDashboard/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=pl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  principles.clinicapp.excelgen:
    image: principles.clinicapp.excelgen:v1.2
    build:
      context: .
      dockerfile: ClinicApp.MSExcelGen/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=pl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  principles.clinicapp.authorizationandusermanager:
    image: principles.clinicapp.authorizationandusermanager:v1.2
    build:
      context: .
      dockerfile: ClinicApp.AuthorizationAndUserManager/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=pl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  principles.clinicapp.client:
    image: principles.clinicapp.client:v1.2
    build:
      context: .
      dockerfile: ClinicApp.Client/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=pl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  principles.clinicapp.contractor:
    image: principles.clinicapp.contractor:v1.2
    build:
      context: .
      dockerfile: ClinicApp.Contractor/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=pl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  principles.clinicapp.infrastructure:
    image: principles.clinicapp.infrastructure:v1.2
    build:
      context: .
      dockerfile: ClinicApp.MSInfrastructure/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=pl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
  principles.clinicapp.servicelog:
    image: principles.clinicapp.servicelog:v1.2
    build:
      context: .
      dockerfile: ClinicApp.ServiceLog/Dockerfile
    restart: always
    expose:
       - 80
       - 443
    environment: 
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__ClinicbdMigrationContext="Host=lin-13704-4133-pgsql-primary.servers.linodedb.net;Database=pl_db;Username=linpostgres;Password=HxywGpAs2-2CnbGh"
