version: '3.4'
services:
  clinicapp.frontend:
    image: raymelguerra/clinicapp-frontend
    restart: always
    ports:
      - 2000:80
      - 2100:443
    depends_on:
      - clinicapp.backend
    env_file:
      - test.env
  clinicapp.backend:
    image: raymelguerra/clinicapp-api
    restart: always
    ports:
       - 2001:8080
       - 2002:8081
    env_file:
      - test.env